### ISSUE TITLE
[Feature] Status columns relies on hard-coded string values

### ISSUE THREAD

**Issue by olivierobert** [pramote-chopaka/nimble-web-assignment#17]
## Issue

The table `submission` and `keywordResult` are structured to use text for statuses. As a result, the value for status is hard-coded in several places, such as services and templates:

https://github.com/pramote-chopaka/nimble-web-assignment/blob/0441a289a33a3719a0cedd9aca316800699706df/src/main/java/chopaka/pramote/nimblewebassignment/service/SubmissionAsyncService.java#L34-L44

It appears that for `keyword_results`, since there are only two possible values, `failed` or `done`, a boolean column could make more sense. 

## Expected

The status values should not be hard-coded, and the status column should use a more appropriate column type.

**Comment by pramote-chopaka** [comment]
The status could possibly be 3 values, `created`, `failed` and `done`. So that's why I chose text column type.
About hard-coded values, I agree that it shouldn't be hard-coded. I'll refactor it to be constants or enum values.

**Comment by pramote-chopaka** [comment]
The fix is merged. However, the impact from this change is status will be displayed in CAPITAL on screen, ex, `DONE` because it's an enum and enum's name is used to displayed.
It will be fixed along with #21

**Comment by olivierobert** [comment]
The fix done in #23 looks good to me and indeed an improvemnt 👍
