### ISSUE TITLE
[Feature] Render the stored raw HTML

### ISSUE THREAD

**Issue by olivierobert** [pramote-chopaka/nimble-web-assignment#18]
## Issue

While the HTML content of the Google search results page is stored correctly in the database, a user cannot verify the accuracy of the scraping since the content is displayed as plain text.

![2565-07-15 13 43 13](https://user-images.githubusercontent.com/696529/179166840-022ea2d1-f221-4e24-8743-5686eb725dbc.gif)

## Expected

Since there are a bit of challenge to render it, the expectation is that you should find a way to render it alongside the keyword search results.

**Comment by pramote-chopaka** [comment]
I thought about rendering it in HTML but it could not be rendered smoothly, ex, broken images/css/js links so I decided to simply return it as plain text.
I'll add the feature to render it along side the result as per your request.

**Comment by pramote-chopaka** [comment]
Fixed and merged. Simply return as text/html and open the link in new tab to let user to compare with the result details.

**Comment by olivierobert** [comment]
Another option would be to use an iframe and insert the content with the `srcdoc` attribute (see [reference](https://www.w3schools.com/tags/att_iframe_srcdoc.asp)). The advantage is that the results could be checked on the same page as teh scraping results 💡
