### ISSUE TITLE
[Bug] Wrong keywords are returned when performing a search

### ISSUE THREAD

**Issue by olivierobert** [pramote-chopaka/nimble-web-assignment#20]
## Issue

Searching for `keywordResult` returns records for which the keyword does not match:

See the below GIF for steps to reproduce:

![2565-07-15 13 55 02](https://user-images.githubusercontent.com/696529/179168706-d4331b74-f814-4d82-b3bc-d3044a46663b.gif)

## Expected

The search should only return the `keywordResult` that contains the searched keyword.

**Comment by pramote-chopaka** [comment]
Searching feature will search the input in HTML result content, not keyword column, that's why it doesn't look like match with  keywords.

If it should match only the submitted keywords (not the content), I'll update it.

**Comment by olivierobert** [comment]
Understood on the current implementation.

The search must indeed match the keyword 😅 From a UX's perspective, it would be hard for a user to understand why it returns matches since they cannot see the stored content. The search might also return a lot of results for no value.
