### ISSUE TITLE
[Question] How would you avoid putting presentation logic in templates?

### ISSUE THREAD

**Issue by olivierobert** [pramote-chopaka/nimble-web-assignment#21]
## Issue

Whether it is for formating dates or displaying the correct status, template files contain presentation logic, thus making it harder to read, test and maintain over time.

https://github.com/pramote-chopaka/nimble-web-assignment/blob/0441a289a33a3719a0cedd9aca316800699706df/src/main/resources/templates/submissions/submission.html#L34-L35

https://github.com/pramote-chopaka/nimble-web-assignment/blob/0441a289a33a3719a0cedd9aca316800699706df/src/main/resources/templates/submissions/list.html#L57-L66

So what would be a better strategy to handle presentation logic?

**Comment by pramote-chopaka** [comment]
One strategy I could think of is creating a presentation utility class. Move the logic to that class and call it in template.

**Comment by pramote-chopaka** [comment]
The fix is merged.

**Comment by olivierobert** [comment]
Indeed, using an object such as a presenter (or sometimes called decorator or carrier) class would be better. It also allows to have such logic unit tests as done in #28
